# Generated by Django 5.2.4 on 2025-07-11 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250711_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete_per',
        ),
        migrations.RemoveField(
            model_name='task',
            name='dead_line',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='upd_date',
        ),
        migrations.AddField(
            model_name='task',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Close Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_action',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Issue/Action'),
        ),
        migrations.AddField(
            model_name='task',
            name='kpi',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('base_layer', 'Base Layer'), ('troubleshooting', 'Troubleshooting'), ('hse', 'HSE'), ('deliverable', 'Deliverable'), ('development', 'Development')], default='project', max_length=20, null=True, verbose_name='KPI'),
        ),
        migrations.AddField(
            model_name='task',
            name='percentage_completion',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of Completion'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality',
            field=models.CharField(blank=True, choices=[('poor', 'Poor'), ('below_average', 'Below Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=15, null=True, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=15, null=True, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='core/task_files/', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('due', 'Due')], default='open', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
