# Generated by Django 5.2.4 on 2025-07-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kpi_alter_task_kpi_qualitytype_alter_task_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['name'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterModelOptions(
            name='qualitytype',
            options={'ordering': ['name'], 'verbose_name': 'Quality Type', 'verbose_name_plural': 'Quality Types'},
        ),
    ]
