# Generated by Django 5.2.4 on 2025-07-15 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_kpi_options_alter_qualitytype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Evaluated By'),
        ),
        migrations.AddField(
            model_name='task',
            name='evaluated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Evaluation Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='evaluation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluation Comments'),
        ),
        migrations.AddField(
            model_name='task',
            name='evaluation_status',
            field=models.CharField(choices=[('pending', 'Pending Evaluation'), ('evaluated', 'Evaluated')], default='pending', max_length=20, verbose_name='Evaluation Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Quality Score (1-10)'),
        ),
    ]
