# Generated by Django 5.2.4 on 2025-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
