# Generated by Django 5.1.4 on 2025-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_alter_kpi_name_alter_qualitytype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='core_custom_user_ty_4f24f0_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['under_supervision'], name='core_custom_under_s_43dcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='core_custom_email_a5d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['created_by'], name='core_kpi_created_117e26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='core_notifi_recipie_9d58cb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='core_notifi_read_bfd411_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read'], name='core_notifi_recipie_10fe77_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitytype',
            index=models.Index(fields=['created_by'], name='core_qualit_created_2b007e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible'], name='core_task_respons_85b199_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='core_task_status_e18e62_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='core_task_priorit_e802be_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='core_task_created_ec551c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['close_date'], name='core_task_close_d_18750a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['evaluation_status'], name='core_task_evaluat_8fe2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['approval_status'], name='core_task_approva_1e79e1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible', 'status'], name='core_task_respons_851551_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible', 'priority'], name='core_task_respons_fd92fb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['close_date', 'status'], name='core_task_close_d_5335c3_idx'),
        ),
    ]
