# Generated by Django 5.1.4 on 2025-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='core_custom_user_ty_4f24f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='core_custom_under_s_43dcf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='core_custom_email_a5d01e_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpi',
            name='core_kpi_created_117e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_9d58cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_read_bfd411_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_created_d0c445_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_10fe77_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitytype',
            name='core_qualit_created_2b007e_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_respons_85b199_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_status_e18e62_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_priorit_e802be_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_created_ec551c_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_close_d_18750a_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_evaluat_8fe2e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_approva_1e79e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_respons_851551_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_respons_fd92fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_close_d_5335c3_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='core/avatar'),
        ),
    ]
