# Generated by Django 5.2.4 on 2025-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='core/img/avatar/blank_profile.png', upload_to='core/avatar'),
        ),
    ]
