# Generated by Django 5.1.4 on 2025-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_qualitytype_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_priority_multiplier', models.FloatField(default=1.2, help_text='Multiplier for high priority tasks (e.g., 1.2 = +20%)', verbose_name='High Priority Multiplier')),
                ('medium_priority_multiplier', models.FloatField(default=1.0, help_text='Multiplier for medium priority tasks (e.g., 1.0 = no change)', verbose_name='Medium Priority Multiplier')),
                ('low_priority_multiplier', models.FloatField(default=1.0, help_text='Multiplier for low priority tasks (e.g., 1.0 = no change)', verbose_name='Low Priority Multiplier')),
                ('early_completion_bonus_per_day', models.FloatField(default=1.0, help_text='Bonus percentage per day for early completion', verbose_name='Early Completion Bonus per Day (%)')),
                ('max_early_completion_bonus', models.FloatField(default=5.0, help_text='Maximum bonus percentage for early completion', verbose_name='Maximum Early Completion Bonus (%)')),
                ('late_completion_penalty_per_day', models.FloatField(default=2.0, help_text='Penalty percentage per day for late completion', verbose_name='Late Completion Penalty per Day (%)')),
                ('max_late_completion_penalty', models.FloatField(default=20.0, help_text='Maximum penalty percentage for late completion', verbose_name='Maximum Late Completion Penalty (%)')),
                ('manager_closure_penalty', models.FloatField(default=20.0, help_text='Penalty percentage when manager closes incomplete task', verbose_name='Manager Closure Penalty (%)')),
                ('evaluation_formula', models.CharField(default='Final Score = (Quality Score × Priority Multiplier) ± Time Bonus/Penalty', help_text='Description of the evaluation formula for reference', max_length=500, verbose_name='Evaluation Formula Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Evaluation Settings',
                'verbose_name_plural': 'Task Evaluation Settings',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='Date when task was actually completed', null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Automatically calculated final score out of 100%', null=True, verbose_name='Final Score (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='manager_closure_penalty_applied',
            field=models.BooleanField(default=False, help_text='Whether manager closure penalty was applied', verbose_name='Manager Closure Penalty Applied'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_multiplier',
            field=models.FloatField(blank=True, help_text='Multiplier applied based on task priority', null=True, verbose_name='Priority Multiplier'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_score_calculated',
            field=models.FloatField(blank=True, help_text='Quality score from QualityType percentage', null=True, verbose_name='Quality Score (Calculated)'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_bonus_penalty',
            field=models.FloatField(blank=True, help_text='Bonus for early completion or penalty for late completion', null=True, verbose_name='Time Bonus/Penalty (%)'),
        ),
    ]
