# Generated by Django 5.1.4 on 2025-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_convert_priority_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, help_text='Expected completion date set at task creation', null=True, verbose_name='Target Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateField(blank=True, help_text='Actual completion date set by manager during evaluation', null=True, verbose_name='Close Date'),
        ),
    ]
