# Generated by Django 5.1.4 on 2025-08-07 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_target_date_alter_task_close_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AddField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this KPI measures', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this KPI is active and used in calculations', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order in which KPIs are displayed', verbose_name='Sort Order'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight percentage for this KPI in employee progress calculation (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Weight (%)'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=100, verbose_name='KPI Name'),
        ),
        migrations.CreateModel(
            name='EmployeeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('total_progress_score', models.FloatField(blank=True, help_text='Overall progress score calculated from KPI performance', null=True, verbose_name='Total Progress Score (%)')),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('progress_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown of progress by KPI', verbose_name='Progress Breakdown')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the progress calculation', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_progress', to=settings.AUTH_USER_MODEL, verbose_name='Calculated By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_progress', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Employee Progress',
                'verbose_name_plural': 'Employee Progress Records',
                'ordering': ['-period_end', '-created_at'],
                'unique_together': {('employee', 'manager', 'period_start', 'period_end')},
            },
        ),
    ]
