# Generated by Django 5.1.4 on 2025-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_task_responsible_status_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], db_index=True, default='pending', max_length=15, null=True, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='evaluation_status',
            field=models.CharField(choices=[('pending', 'Pending Evaluation'), ('evaluated', 'Evaluated')], db_index=True, default='pending', max_length=20, verbose_name='Evaluation Status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', 'created_at'], name='notif_rec_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_date'], name='task_created_date_idx'),
        ),
    ]
