# Generated by Django 5.2.5 on 2025-08-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_submission',
            field=models.TextField(blank=True, help_text='Employee-provided textual submission when no file is attached', null=True, verbose_name='Employee Submission'),
        ),
    ]
