# Generated by Django 5.2.5 on 2025-08-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_employee_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('disapproved', 'Disapproved')], db_index=True, default='disapproved', max_length=15, null=True, verbose_name='Approval Status'),
        ),
    ]
