# Generated by Django 5.1.4 on 2025-10-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_taskreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Note Title')),
                ('content', models.TextField(verbose_name='Note Content')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flag this note for quick access', verbose_name='Flagged/Starred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='User for whom this note is created', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_notes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('related_task', models.ForeignKey(blank=True, help_text='Optional: Link this note to a specific task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.task', verbose_name='Related Task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField(db_index=True, verbose_name='Reminder Date')),
                ('message', models.TextField(blank=True, help_text='Optional custom message for the reminder', null=True, verbose_name='Reminder Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note_reminders', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.note')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['assigned_to', 'is_flagged', '-created_at'], name='note_assigned_flagged_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by', '-created_at'], name='note_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='notereminder',
            index=models.Index(fields=['scheduled_for', 'recipient'], name='note_reminder_sched_rcpt_idx'),
        ),
    ]
