# Generated by Django 5.1.4 on 2025-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_note_and_notereminder_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notereminder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this recurring reminder is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='notereminder',
            name='last_sent_date',
            field=models.DateField(blank=True, help_text='Date when this reminder was last sent', null=True, verbose_name='Last Sent Date'),
        ),
        migrations.AddField(
            model_name='notereminder',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='How often to send this reminder', max_length=10, verbose_name='Recurrence Type'),
        ),
        migrations.AddIndex(
            model_name='notereminder',
            index=models.Index(fields=['recurrence_type', 'is_active'], name='note_reminder_recurrence_idx'),
        ),
    ]
