# Generated by Django 5.2.5 on 2025-10-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_recurring_reminder_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notereminder',
            name='note_reminder_recurrence_idx',
        ),
        migrations.RemoveField(
            model_name='notereminder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='notereminder',
            name='last_sent_date',
        ),
        migrations.RemoveField(
            model_name='notereminder',
            name='recurrence_type',
        ),
    ]
