# Generated by Django 5.2.5 on 2025-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_notereminder_note_reminder_recurrence_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notereminder',
            name='repeat_interval',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('weekly', 'Every week'), ('monthly', 'Every month')], db_index=True, default='none', help_text='Automatically create the next reminder after sending', max_length=10, verbose_name='Repeat'),
        ),
    ]
